(function (root, factory) {
    if (typeof module === "object" && module.exports) {
        module.exports = factory();
        return;
    }

    root.__LAWYER_SEED_DIRECTORY__ = factory();
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
    return [
        {
            id: "lawyer-seed-01",
            fullName: "Temur Nurmukhamedov",
            specialty: "Korporativ va investitsiya huquqi",
            city: "Toshkent",
            experienceYears: 13,
            phone: "+998 71 234 39 06",
            consultationFee: "Kelishiladi",
            bio: "GRAVAMEN FIDELIS FIDES jamoasida investitsiya loyihalari, kompaniya tuzilmalari va strategik shartnomalarni huquqiy hamrohlik qiladi.",
            formats: ["Online", "Offline"],
            leadCount: 118,
            ratingBase: 4.8,
            verified: true
        },
        {
            id: "lawyer-seed-02",
            fullName: "Nodir Rasulov",
            specialty: "Telekom, IP va mehnat huquqi",
            city: "Toshkent",
            experienceYears: 12,
            phone: "+998 71 234 39 06",
            consultationFee: "Kelishiladi",
            bio: "Telekommunikatsiya, intellektual mulk va mehnat munosabatlari bo'yicha biznes mijozlarga amaliy yechimlar taklif qiladi.",
            formats: ["Online", "Offline"],
            leadCount: 101,
            ratingBase: 4.7,
            verified: true
        },
        {
            id: "lawyer-seed-03",
            fullName: "Laziz Tursunov",
            specialty: "Sud va arbitraj nizolari",
            city: "Toshkent",
            experienceYears: 10,
            phone: "+998 71 234 39 06",
            consultationFee: "Kelishiladi",
            bio: "Tijorat nizolari, sud vakilligi va arbitraj jarayonlarida hujjat strategiyasi hamda dalil bazasini tayyorlash bilan ishlaydi.",
            formats: ["Offline", "Online"],
            leadCount: 93,
            ratingBase: 4.6,
            verified: true
        },
        {
            id: "lawyer-seed-04",
            fullName: "Farxod Soipov",
            specialty: "Tashqi savdo va tijorat shartnomalari",
            city: "Toshkent",
            experienceYears: 9,
            phone: "+998 71 234 39 06",
            consultationFee: "Kelishiladi",
            bio: "Eksport-import bitimlari, kontrakt tahlili va kontragentlar bilan tijorat munosabatlarini xavfsiz yuritishga ixtisoslashgan.",
            formats: ["Online", "Offline"],
            leadCount: 87,
            ratingBase: 4.5,
            verified: true
        },
        {
            id: "lawyer-seed-05",
            fullName: "Akmal Xasanov",
            specialty: "Biznes va soliq nizolari",
            city: "Toshkent",
            experienceYears: 18,
            phone: "+998 88 101 00 04",
            consultationFee: "Kelishiladi",
            bio: "Veritas Inter Lex boshqaruvchi hamkori sifatida xo'jalik subyektlari sud ishlari va soliq tekshiruvlarida keng amaliyotga ega.",
            formats: ["Online", "Offline"],
            leadCount: 122,
            ratingBase: 4.8,
            verified: true
        },
        {
            id: "lawyer-seed-06",
            fullName: "Ahrorjon Boltaboev",
            specialty: "Mediatsiya va korporativ nizolar",
            city: "Toshkent",
            experienceYears: 11,
            phone: "+998 88 101 00 04",
            consultationFee: "Kelishiladi",
            bio: "Mediatsiya, korporativ kelishmovchiliklar va muzokara asosida nizolarni yumshoq hal qilish amaliyoti bilan tanilgan.",
            formats: ["Online", "Offline"],
            leadCount: 89,
            ratingBase: 4.6,
            verified: true
        },
        {
            id: "lawyer-seed-07",
            fullName: "Farruhmirzo G'aybullayev",
            specialty: "Korporativ va xo'jalik huquqi",
            city: "Toshkent",
            experienceYears: 8,
            phone: "+998 88 101 00 04",
            consultationFee: "Kelishiladi",
            bio: "Yuridik shaxslar faoliyatini doimiy hamrohlik qilish, ichki hujjatlar va xo'jalik munosabatlarini tartibga solishga ixtisoslashgan.",
            formats: ["Online", "Offline"],
            leadCount: 76,
            ratingBase: 4.5,
            verified: true
        },
        {
            id: "lawyer-seed-08",
            fullName: "Saidislom Erkinxo'jayev",
            specialty: "Davlat organlari bilan nizolar",
            city: "Toshkent",
            experienceYears: 8,
            phone: "+998 88 101 00 04",
            consultationFee: "Kelishiladi",
            bio: "Ma'muriy tartibdagi kelishmovchiliklar, davlat organlari qarorlariga e'tiroz va vakillik ishlarida faol ishlaydi.",
            formats: ["Offline", "Online"],
            leadCount: 74,
            ratingBase: 4.4,
            verified: true
        },
        {
            id: "lawyer-seed-09",
            fullName: "Mohirjon Rustamov",
            specialty: "Ijro va qarzdorlik ishlari",
            city: "Toshkent",
            experienceYears: 7,
            phone: "+998 88 101 00 04",
            consultationFee: "Kelishiladi",
            bio: "Ijro hujjatlari, qarzdorlikni undirish va xo'jalik yurituvchi subyektlar manfaatini himoya qilish bo'yicha yordam beradi.",
            formats: ["Online", "Offline"],
            leadCount: 68,
            ratingBase: 4.4,
            verified: true
        },
        {
            id: "lawyer-seed-10",
            fullName: "Jamshidjon Astanov",
            specialty: "Ko'chmas mulk va qurilish huquqi",
            city: "Toshkent",
            experienceYears: 7,
            phone: "+998 88 101 00 04",
            consultationFee: "Kelishiladi",
            bio: "Qurilish loyihalari, ko'chmas mulk bitimlari va mulkiy xavflarni baholash bo'yicha huquqiy hamrohlik ko'rsatadi.",
            formats: ["Offline", "Online"],
            leadCount: 66,
            ratingBase: 4.4,
            verified: true
        },
        {
            id: "lawyer-seed-11",
            fullName: "Gulshoda Askarbekova",
            specialty: "Meros va fuqarolik ishlari",
            city: "Toshkent",
            experienceYears: 18,
            phone: "+998 97 778 95 40",
            consultationFee: "Bepul dastlabki konsultatsiya",
            bio: "Askarbekova Partner yetakchi advokati sifatida meros, shartnomalar va mulkiy nizolarda ko'p yillik sud amaliyotiga ega.",
            formats: ["Offline", "Online"],
            leadCount: 116,
            ratingBase: 4.8,
            verified: true
        },
        {
            id: "lawyer-seed-12",
            fullName: "Nilufar Shuybekova",
            specialty: "Oilaviy va fuqarolik ishlari",
            city: "Toshkent",
            experienceYears: 9,
            phone: "+998 97 778 95 40",
            consultationFee: "Bepul dastlabki konsultatsiya",
            bio: "Oilaviy kelishmovchiliklar, aliment, nikohni bekor qilish va fuqarolik da'volari bo'yicha amaliy maslahatlar beradi.",
            formats: ["Online", "Offline"],
            leadCount: 92,
            ratingBase: 4.7,
            verified: true
        },
        {
            id: "lawyer-seed-13",
            fullName: "Murad Askarbekov",
            specialty: "Jinoyat va ma'muriy himoya",
            city: "Toshkent",
            experienceYears: 10,
            phone: "+998 97 778 95 40",
            consultationFee: "Bepul dastlabki konsultatsiya",
            bio: "Tergovdan tortib sudgacha bo'lgan bosqichlarda himoya, ma'muriy jarimalar va protsessual strategiya ustida ishlaydi.",
            formats: ["Offline", "Online"],
            leadCount: 88,
            ratingBase: 4.6,
            verified: true
        },
        {
            id: "lawyer-seed-14",
            fullName: "Zebo Muradova",
            specialty: "Biznesni yuridik qo'llab-quvvatlash",
            city: "Toshkent",
            experienceYears: 8,
            phone: "+998 97 778 95 40",
            consultationFee: "Bepul dastlabki konsultatsiya",
            bio: "Kompaniyalarni ro'yxatdan o'tkazish, shartnomalar, ishchi munosabatlari va kundalik yuridik support uchun mos mutaxassis.",
            formats: ["Online", "Offline"],
            leadCount: 79,
            ratingBase: 4.5,
            verified: true
        },
        {
            id: "lawyer-seed-15",
            fullName: "Nadejda Pak",
            specialty: "Jinoyat, ma'muriy va iqtisodiy ishlar",
            city: "Toshkent",
            experienceYears: 14,
            phone: "+998 90 992 26 14",
            consultationFee: "Kelishiladi",
            bio: "LEGAL CASE asoschisi bo'lib, jinoyat, ma'muriy, iqtisodiy ishlar, korporativ support va mediatsiya bo'yicha ishlaydi.",
            formats: ["Online", "Offline"],
            leadCount: 114,
            ratingBase: 4.8,
            verified: true
        },
        {
            id: "lawyer-seed-16",
            fullName: "Nargiza Tashteva",
            specialty: "Mediatsiya va maishiy nizolar",
            city: "Toshkent",
            experienceYears: 12,
            phone: "+998 71 221 72 25",
            consultationFee: "200 000 so'm",
            bio: "Real Protection boshqaruvchi hamkori va professional mediator sifatida oilaviy, uy-joy va muzokara orqali hal etiladigan nizolarni yuritadi.",
            formats: ["Offline", "Online"],
            leadCount: 97,
            ratingBase: 4.7,
            verified: true
        },
        {
            id: "lawyer-seed-17",
            fullName: "Mukarrama Umarova",
            specialty: "Oilaviy, meros va mehnat nizolari",
            city: "Toshkent",
            experienceYears: 9,
            phone: "+998 71 221 72 25",
            consultationFee: "200 000 so'm",
            bio: "Oilaviy, meros, mehnat va ma'muriy huquqbuzarlik ishlari bo'yicha jismoniy shaxslar manfaatini himoya qiladi.",
            formats: ["Online", "Offline"],
            leadCount: 73,
            ratingBase: 4.5,
            verified: true
        },
        {
            id: "lawyer-seed-18",
            fullName: "Allan Pashkovskiy",
            specialty: "Axborot va korporativ huquq",
            city: "Toshkent",
            experienceYears: 16,
            phone: "+998 71 209 11 67",
            consultationFee: "Kelishiladi",
            bio: "Acceptus boshqaruvchi hamkori bo'lib, axborot huquqi, korporativ masalalar va biznesni qayta tuzish loyihalarida chuqur tajribaga ega.",
            formats: ["Offline", "Online"],
            leadCount: 111,
            ratingBase: 4.8,
            verified: true
        },
        {
            id: "lawyer-seed-19",
            fullName: "Aziz Sattarov",
            specialty: "Jinoyat huquqi va himoya",
            city: "Toshkent",
            experienceYears: 13,
            phone: "+998 71 209 11 67",
            consultationFee: "Kelishiladi",
            bio: "Acceptus jamoasida jinoyat ishlari, protsessual himoya va inson huquqlari bilan bog'liq murakkab case'larda ishlaydi.",
            formats: ["Offline", "Online"],
            leadCount: 95,
            ratingBase: 4.7,
            verified: true
        },
        {
            id: "lawyer-seed-20",
            fullName: "Leonid Tselishchev",
            specialty: "Mualliflik huquqi va intellektual mulk",
            city: "Toshkent",
            experienceYears: 12,
            phone: "+998 97 444 11 04",
            consultationFee: "Bepul dastlabki konsultatsiya",
            bio: "VERDICT boshqaruvchi hamkori sifatida mualliflik huquqlari, brend himoyasi va tijorat intellektual aktivlari bilan shug'ullanadi.",
            formats: ["Online", "Offline"],
            leadCount: 99,
            ratingBase: 4.7,
            verified: true
        },
        {
            id: "lawyer-seed-21",
            fullName: "Aleksey Pilev",
            specialty: "Ma'muriy va davlat organlari nizolari",
            city: "Toshkent",
            experienceYears: 10,
            phone: "+998 97 409 42 43",
            consultationFee: "Bepul dastlabki konsultatsiya",
            bio: "Tadbirkorlar huquqini himoya qilish, tekshiruvlar va ma'muriy sudlarda vakillik qilishga yo'naltirilgan amaliyot yuritadi.",
            formats: ["Offline", "Online"],
            leadCount: 82,
            ratingBase: 4.6,
            verified: true
        },
        {
            id: "lawyer-seed-22",
            fullName: "Vladislav Tsvetkov",
            specialty: "Fuqarolik va iqtisodiy nizolar",
            city: "Toshkent",
            experienceYears: 9,
            phone: "+998 97 444 11 04",
            consultationFee: "Bepul dastlabki konsultatsiya",
            bio: "Shartnoma, qarzdorlik, mulk va boshqa fuqarolik-iqtisodiy nizolar bo'yicha sud hamda sudgacha vakillik qiladi.",
            formats: ["Online", "Offline"],
            leadCount: 78,
            ratingBase: 4.5,
            verified: true
        },
        {
            id: "lawyer-seed-23",
            fullName: "Doniyor Nurmakhmadov",
            specialty: "Kripto va raqamli aktivlar huquqi",
            city: "Toshkent",
            experienceYears: 8,
            phone: "+998 97 409 42 43",
            consultationFee: "Bepul dastlabki konsultatsiya",
            bio: "Kriptoaktivlar, blokcheyn loyihalari va raqamli bizneslar uchun huquqiy support hamda risklarni pasaytirish ustida ishlaydi.",
            formats: ["Online", "Offline"],
            leadCount: 71,
            ratingBase: 4.5,
            verified: true
        },
        {
            id: "lawyer-seed-24",
            fullName: "Sherzod Egamberdiyev",
            specialty: "Korporativ, investitsiya va ko'chmas mulk huquqi",
            city: "Toshkent",
            experienceYears: 15,
            phone: "+998 98 100 33 44",
            consultationFee: "Kelishiladi",
            bio: "Sher Legal asoschisi bo'lib, bizneslarni kompleks hamrohlik qilish, investitsiya bitimlari va ko'chmas mulk loyihalariga ixtisoslashgan.",
            formats: ["Offline", "Online"],
            leadCount: 125,
            ratingBase: 4.9,
            verified: true
        },
        {
            id: "lawyer-seed-25",
            fullName: "Yunus Ernazarov",
            specialty: "Fuqarolik, iqtisodiy va tijorat masalalari",
            city: "Toshkent",
            experienceYears: 8,
            phone: "+998 98 100 33 44",
            consultationFee: "Kelishiladi",
            bio: "Mediator va boshqaruvchi hamkor sifatida fuqarolik-iqtisodiy yo'nalish, komplayens va korporativ boshqaruvda faol ishlaydi.",
            formats: ["Online", "Offline"],
            leadCount: 104,
            ratingBase: 4.8,
            verified: true
        },
        {
            id: "lawyer-seed-26",
            fullName: "Farrux Xodiev",
            specialty: "Fuqarolik va iqtisodiy ishlar",
            city: "Toshkent",
            experienceYears: 7,
            phone: "+998 98 100 33 44",
            consultationFee: "Kelishiladi",
            bio: "Fuqarolik nizolari, iqtisodiy da'volar va biznes subyektlari vakilligida amaliy tajribaga ega Sher Legal advokati.",
            formats: ["Online", "Offline"],
            leadCount: 84,
            ratingBase: 4.6,
            verified: true
        },
        {
            id: "lawyer-seed-27",
            fullName: "Osman Latipov",
            specialty: "Jinoyat va ma'muriy ishlar",
            city: "Toshkent",
            experienceYears: 10,
            phone: "+998 98 100 33 44",
            consultationFee: "Kelishiladi",
            bio: "Jinoyat huquqi amaliyoti rahbari bo'lib, tergov organlari tajribasi asosida himoya strategiyasini quradi.",
            formats: ["Offline", "Online"],
            leadCount: 109,
            ratingBase: 4.8,
            verified: true
        },
        {
            id: "lawyer-seed-28",
            fullName: "Abdullo Axmedov",
            specialty: "Jinoyat, ma'muriy, fuqarolik va iqtisodiy ishlar",
            city: "Toshkent",
            experienceYears: 9,
            phone: "+998 98 100 33 44",
            consultationFee: "Kelishiladi",
            bio: "Bir nechta yo'nalishda ishlovchi universal advokat bo'lib, jinoyat va iqtisodiy ishlarda protsessual vakillik olib boradi.",
            formats: ["Offline", "Online"],
            leadCount: 91,
            ratingBase: 4.7,
            verified: true
        },
        {
            id: "lawyer-seed-29",
            fullName: "Davron Idrisxujaev",
            specialty: "Hamkor advokat va sud vakilligi",
            city: "Toshkent",
            experienceYears: 8,
            phone: "+998 98 100 33 44",
            consultationFee: "Kelishiladi",
            bio: "Sher Legal hamkor advokati sifatida sud hujjatlari, mijoz vakilligi va murakkab protsessual ishlarni yuritadi.",
            formats: ["Online", "Offline"],
            leadCount: 77,
            ratingBase: 4.5,
            verified: true
        },
        {
            id: "lawyer-seed-30",
            fullName: "Shohrux Yakuubbayev",
            specialty: "Jinoyat va ma'muriy ishlar",
            city: "Toshkent",
            experienceYears: 7,
            phone: "+998 98 100 33 44",
            consultationFee: "Kelishiladi",
            bio: "Jinoyat va ma'muriy yo'nalishlarda himoya yuritadi, ayniqsa tezkor protsessual aralashuv talab qiladigan vaziyatlarda faol.",
            formats: ["Offline", "Online"],
            leadCount: 72,
            ratingBase: 4.5,
            verified: true
        }
    ];
});
